name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Clean, just in case
      run: make clean

    - name: Make a release build
      run: make release

    - name: Check (and, in the process, make a debug build)
      run: make check
